name: Deployment to Server

on:
  push:
    branches: [ "Nonprod" ] # รันอัตโนมัติเมื่อบอทจาก App Repo ส่ง Tag ใหม่มาที่กิ่งนี้

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. เข้าไปที่โฟลเดอร์โปรเจกต์ (ถ้าไม่มีให้ Clone โดยระบุ Branch Nonprod)
            cd /home/apiadmin/deploy-customer-api || git clone -b Nonprod https://github.com/kitsanaphon1/deploy-customer-api.git /home/apiadmin/deploy-customer-api
            
            cd /home/apiadmin/deploy-customer-api
            
            # 2. ดึงไฟล์ล่าสุดจากกิ่ง Nonprod (ห้ามใช้ main เพราะบอทส่งมาที่นี่)
            git pull origin Nonprod
            
            # 3. สั่งรัน Docker (จะดึง Image v1.8, v1.9... ตามที่ระบุใน compose)
            docker compose pull
            docker compose up -d
            
            # 4. ล้าง Image เก่าที่ไม่ได้ใช้งาน
            docker image prune -f